- name : Main NGINX config file
  copy:
    src: nginx.conf # pas besoin de préciser de path, il sait qu'il doit chercher dans le dossier files/
    dest: /etc/nginx/nginx.conf
  notify:
    - Edited config

- name: Open firewall port for NGINX
    firewalld:
    port: "{{ nginx_port}}"/tcp
    permanent: yes
    state: enabled
      