- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
  user:
    name: "{{ item }}"
    comment: Added from users var
    group: admin
  with_items: "{{ users }}" # ceci permet de boucler sur la liste users
